"""Initial migration.

Revision ID: d49b8cc42de9
Revises: 
Create Date: 2023-09-28 13:23:15.921116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd49b8cc42de9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_stock')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_stock',
    sa.Column('itemName', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('itemName')
    )
    # ### end Alembic commands ###
